substitutions:
  myname: nml-techfire-0
  myname_underscores: nml_techfire_0

esphome:
  comment: "Wireless MCU that could go in TechFire (MI-136)."
    
esp32:
  board: esp-wrover-kit
  framework:
    version: 1.0.6
    source: ~3.10006.0
    platform_version: platformio/espressif32 @ 3.5.0
    type: arduino
  variant: ESP32

packages:
  esphome: !include ./esphome.yaml
  api: !include ./api.yaml
  ota: !include ./ota.yaml
  wifi: !include ./wifi.yaml
  logger: !include ./logger.yaml