substitutions:
  myname: nml-sensors-0

esphome:
  comment: "Wireless MCU for sync devices (presumably in Wean)."
  on_boot:
    priority: 800.0
    then:
      - switch.turn_off: syncd

esp8266:
  board: nodemcu

packages:
  esphome: !include ./esphome.yaml
  api: !include ./api.yaml
  ota: !include ./ota.yaml
  wifi: !include ./wifi.yaml
  logger: !include ./logger.yaml
   
switch:
  - platform: gpio
    pin: 
        number: GPIO2
        inverted: false
        mode:
            output: true
    name: ${myname} Blue LED Debug Output
    icon: mdi:led-on
    id: syncd

binary_sensor:    
  - platform: gpio
    pin: 
        number: GPIO5
        inverted: false
        mode:
            input: true
            pullup: false 
    name: ${myname} TTL-0
    icon: mdi:switch

  - platform: gpio
    pin: 
        number: GPIO4
        inverted: false
        mode:
            input: true
            pullup: false 
    name: ${myname} TTL-1
    icon: mdi:switch
        
  - platform: gpio
    pin: 
        number: GPIO14
        inverted: false
        mode:
            input: true
            pullup: false 
    name: ${myname} TTL-2
    icon: mdi:switch
        
  - platform: gpio
    pin: 
        number: GPIO12
        inverted: false
        mode:
            input: true
            pullup: false 
    name: ${myname} TTL-3
    icon: mdi:switch

  - platform: gpio
    pin: 
        number: GPIO13
        inverted: false
        mode:
            input: true
            pullup: false 
    name: ${myname} TTL-4
    icon: mdi:switch

  - platform: gpio
    pin: 
        number: GPIO3
        inverted: false
        mode:
            input: true
            pullup: false 
    name: ${myname} TTL-5
    icon: mdi:switch

  - platform: gpio
    pin: 
        number: GPIO10
        inverted: false
        mode:
            input: true
            pullup: false 
    name: ${myname} TTL-6
    icon: mdi:switch

  - platform: gpio
    pin: 
        number: GPIO9
        inverted: false
        mode:
            input: true
            pullup: false
    name: ${myname} TTL-7
    icon: mdi:switch       
