substitutions:
  myname: nml-ble-1
  myname_underscores: nml_ble_1
  
esphome:
  comment: "ESP-WROOM-32 used to test joystick analog input signals."

esp32:
  board: nodemcu-32s
  framework:
    version: 1.0.6
    source: ~3.10006.0
    platform_version: platformio/espressif32 @ 3.5.0
    type: arduino
  variant: ESP32

packages:
  esphome: !include ./esphome.yaml
  api: !include ./api.yaml
  ota: !include ./ota.yaml
  wifi: !include ./wifi.yaml
  logger: !include ./logger.yaml

sensor:
  - platform: adc
    pin: GPIO34
    name: ${myname} X
    accuracy_decimals: 3
    update_interval: 0.025s
    unit_of_measurement: "%"
    raw: false
    attenuation: auto
    filters:
        - exponential_moving_average: 
            alpha: 0.1
            send_every: 4
        - lambda: return  x;
        - calibrate_linear:
            - 0.50 -> 0.0
            - 2.85 -> 100.0
    state_class: "measurement"
    
  - platform: adc
    pin: GPIO35
    name: ${myname} Y
    accuracy_decimals: 3
    update_interval: 0.025s
    unit_of_measurement: "%"
    raw: false
    attenuation: auto
    filters:
        - exponential_moving_average: 
            alpha: 0.1
            send_every: 4
        - lambda: return  x;
        - calibrate_linear:
            - 0.45 -> 0.0
            - 2.95 -> 100.0
    state_class: "measurement"