substitutions:
  myname: nml-wrist-0

esphome:
  comment: "Wireless MCU for sync devices (presumably in Wean)."

esp8266:
  board: nodemcu

packages:
  esphome: !include ./esphome.yaml
  api: !include ./api.yaml
  ota: !include ./ota.yaml
  wifi: !include ./wifi.yaml
  font: !include ./font.yaml
  time: !include ./time.yaml
    
sensor:
  - platform: homeassistant
    id: cyno_humidity
    entity_id: sensor.humidity_cynos
    internal: true

  - platform: homeassistant
    id: cyno_temperature
    entity_id: sensor.room_temperature_cynos
    internal: true
    
  - platform: adc
    pin: A0
    name: "Microphone"
    update_interval: 0.025s
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 100
    
spi:
  clk_pin: D5
  mosi_pin: D6

# Example configuration entry
display:
  - platform: st7735
    model: "INITR_GREENTAB"
    reset_pin: D4
    cs_pin: D8
    dc_pin: D7
    rotation: 0
    device_width: 128
    device_height: 128
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 5s
    lambda: |-
      it.printf(0, 0, id(font1), TextAlign::TOP_CENTER, "Cyno Stats");
      it.strftime(0, 60, id(font2), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());
      // Print cyno temperature (from homeassistant sensor)
      //if (id(cyno_temperature).has_state()) {
      //  it.printf(127, 23, id(font3), TextAlign::TOP_RIGHT , "%.1f°", id(cyno_temperature).state);
      //}
      // Print cyno humidity (from homeassistant sensor)
      //if (id(cyno_humidity).has_state()) {
      //  it.printf(127, 60, id(font3), TextAlign::BASELINE_RIGHT , "%.1f°", id(cyno_humidity).state);
      //}