substitutions:
  myname: nml-cam-0

esphome:
  name: $myname
  platform: ESP32
  board: esp32dev
  comment: "ESP32-CAM board for development purposes."
  name_add_mac_suffix: false
  project:
    name: "nml.sensors"
    version: "1.0.1"
    
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 30 fps
  idle_framerate: 0.1 fps
  name: 115L-Camera

packages:
  api: !include ./api.yaml
  ota: !include ./ota.yaml
  wifi: !include ./wifi.yaml
  logger: !include ./logger.yaml

switch:
    platform: gpio
    pin: GPIO4
    name: Max-Cam Flash
    icon: mdi:flash
    