substitutions:
  myname: nml-rig-0
  myname_underscores: nml_rig_0

esphome:
  comment: "Wireless MCU for NML-NHP rig room (MI-125k as of 2022-10-16)."

esp8266:
  board: nodemcu

packages:
  esphome: !include ./esphome.yaml
  api: !include ./api.yaml
  ota: !include ./ota.yaml
  wifi: !include ./wifi.yaml
  logger: !include ./logger.yaml
    
text_sensor:
  - platform: homeassistant
    id: rig_125k_monkey
    entity_id: input_text.rig_125k_monkey
    icon: mdi:rotate-orbit
    internal: true
    
sensor:
  - platform: homeassistant
    id: rig_125k_trials_total
    entity_id: counter.rig_125k_trials_worked
    icon: mdi:rotate-orbit
    internal: true
    
  - platform: template
    name: "Total Trials Sensor"
    update_interval: 10s
    accuracy_decimals: 0
    icon: mdi:rotate-orbit
    lambda: !lambda |-
      return id(rig_125k_trials_total).state;
    
  - platform: homeassistant
    id: rig_125k_trials_successful
    entity_id: counter.rig_125k_trials_successful
    icon: mdi:rotate-orbit
    internal: true
    
  - platform: template
    name: "Successful Trials Sensor"
    update_interval: 10s
    accuracy_decimals: 0    
    icon: mdi:rotate-orbit
    lambda: !lambda |-
      return id(rig_125k_trials_successful).state;
      
  - platform: homeassistant
    id: rig_125k_initial_water
    entity_id: input_number.initial_rig_125k_water_volume
    icon: mdi:water-check
    internal: true    
    
  - platform: template
    name: "Wrist Water Consumed"
    id: ${myname_underscores}_water_consumed
    update_interval: 30s
    accuracy_decimals: 0
    icon: mdi:water-minus
    lambda: !lambda |-
      return max(id(rig_125k_initial_water).state - id(${myname_underscores}_water).state, (float) 0.0);
      
  - platform: hx711
    name: ${myname} Water
    id: ${myname_underscores}_water
    dout_pin: D0
    clk_pin: D1
    gain: 64
    update_interval: 2.0s
    accuracy_decimals: 1
    unit_of_measurement: mL
    icon: mdi:water
    filters:
      - median:
          window_size: 30
          send_every: 10
          send_first_at: 3
      - calibrate_linear:
        -  -785200 -> 1000.0
        -  -781050 -> 750.0
        -  -779600 -> 500.0
        -  -778500 -> 365.0
        -  -774750 -> 225.0
        -  -773500 -> 110.0
        -  -772100 -> 0.0
      - lambda: return min(max(((float)2.0) * x, (float) 0.0), (float) 1000.0);
          
  - platform: dht
    pin: D6
    temperature:
      name: ${myname} Temperature DHT11
      id: ${myname_underscores}_temperature
      icon: "mdi:home-thermometer"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 1
      unit_of_measurement: "°F"
      filters:                                                   
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
        - lambda: return x * (9.0/5.0) + 32.0;
    humidity:
      name: ${myname} Humidity DHT11
      id: ${myname_underscores}_humidity
      icon: "mdi:water-percent"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 1
      unit_of_measurement: "%"
      filters: 
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
    update_interval: 5s
    model: DHT11

switch:
  - platform: gpio
    pin:
      number: D4
      mode:
        output: true
    name: ${myname} Indicator
    id: ${myname_underscores}_indicator
    
binary_sensor:
  - platform: gpio
    pin: 
      number: D3
      mode: 
        input: true
        pullup: true
    name: ${myname} Filled
    id: ${myname_underscores}_filled
    icon: mdi:cup-water
    filters: 
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        - wait_until:
            condition:
              api.connected:
        - homeassistant.event:
            event: esphome.button_pressed
            data: 
              message: Filled
        - switch.toggle: ${myname_underscores}_indicator
        - delay: 0.25s
        - switch.toggle: ${myname_underscores}_indicator
        - delay: 0.25s
        - switch.toggle: ${myname_underscores}_indicator
        - delay: 0.25s
        - switch.toggle: ${myname_underscores}_indicator

  - platform: gpio
    pin: 
      number: D5
      mode:
        input: true
        pullup: true
      inverted: true
    icon: mdi:signal-variant
    name: ${myname} Sound Detected
    id: ${myname_underscores}_sound_detected
    device_class: sound
    filters: 
      - delayed_off: 1s

  - platform: gpio
    pin: 
      number: D7
      mode: 
        input: true
        pullup: true
      inverted: true
    name: ${myname} Light
    id: ${myname_underscores}_light
    icon: mdi:lightbulb-question
    publish_initial_state: true
    device_class: light
    filters: 
      - delayed_on: 250ms
      - delayed_off: 250ms
    on_state:
      if:
        condition:
          binary_sensor.is_on: ${myname_underscores}_light
        then:
          - switch.turn_off: ${myname_underscores}_indicator
        else: 
          - switch.turn_on: ${myname_underscores}_indicator
