substitutions:
  myname: nml-cynos-1
  myname_underscores: nml_cynos_1
  
esphome:
  comment: "ESP-WROOM-32 in BRIDGE with different sensors attached."

esp32:
  board: nodemcu-32s
  framework:
    version: 1.0.6
    source: ~3.10006.0
    platform_version: platformio/espressif32 @ 3.5.0
    type: arduino
  variant: ESP32

packages:
  esphome: !include ./esphome.yaml
  api: !include ./api.yaml
  ota: !include ./ota.yaml
  wifi: !include ./wifi.yaml
  logger: !include ./logger.yaml

switch:
  - platform: gpio
    name: ${myname} Light Dark Phase
    pin: GPIO2
    icon: "mdi:led-on"
    device_class: "switch"
    entity_category: "diagnostic"
    id: cynos_light_dark_phase
    
sensor:        
  - platform: dht
    pin: GPIO21
    temperature:
      name: ${myname} Temperature DHT11
      icon: "mdi:home-thermometer"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 1
      unit_of_measurement: "°F"
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
        - lambda: return x * (9.0/5.0) + 32.0;
    humidity:
      name: ${myname} Humidity DHT11
      icon: "mdi:water-percent"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 1
      unit_of_measurement: "%"
      filters: 
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
    update_interval: 5s
    model: DHT11
    
  - platform: dht
    pin: GPIO23
    temperature:
      name: ${myname} Temperature DHT22
      icon: "mdi:home-thermometer"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 1
      unit_of_measurement: "°F"
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
        - lambda: return x * (9.0/5.0) + 32.0;
    humidity:
      name: ${myname} Humidity DHT22
      icon: "mdi:water-percent"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 1
      unit_of_measurement: "%"
      filters: 
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
    update_interval: 5s
    model: DHT22
          
          
  - platform: adc
    pin: GPIO32
    name: ${myname} Sound
    update_interval: 0.01s
    unit_of_measurement: "dB"
    raw: false
    attenuation: auto
    icon: mdi:microphone
    filters:
      - sliding_window_moving_average:
          window_size: 50
          send_every: 25
      - lambda: return 1000.0 * (3.3 - x);
      - calibrate_linear:
        - 125.0 -> 25.0
        - 275.0 -> 60.0
          
  - platform: adc
    pin: GPIO34
    name: ${myname} Illuminance
    accuracy_decimals: 1
    update_interval: 0.05s
    unit_of_measurement: "lux"
    raw: false
    attenuation: auto
    filters:
        - sliding_window_moving_average: 
            window_size: 100
            send_every: 20
        - lambda: return  100.0 * (2.5 - x) + 75.0;
    on_value_range:
      - above: 35.0
        then:
          - switch.turn_on: cynos_light_dark_phase
      - below: 35.0
        then:
          - switch.turn_off: cynos_light_dark_phase
    id: light
    device_class: "illuminance"
    state_class: "measurement"
          
binary_sensor:
  - platform: gpio
    pin: GPIO25
    name: ${myname} PIR
    device_class: motion
    publish_initial_state: true